services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      TZ: Europe/Stockholm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/public:/var/www/public:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl:/etc/ssl:ro
    depends_on:
      - php
      - node
      - python
    networks:
      - app-network
    env_file:
      - .env

  php:
    build: ./docker/php
    image: lemp-php:dev
    container_name: php
    restart: unless-stopped
    command: php-fpm
    volumes:
      - ./www:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
    networks:
      - app-network
    environment:
      TZ: Europe/Stockholm
    env_file:
      - .env

  mariadb:
    image: mariadb:latest
    #security_opt:
    #- seccomp:unconfined
    #cap_add:
    #- SYS_ADMIN
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 2s
      retries: 15
      start_period: 30s
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: statTrack
      TZ: Europe/Stockholm
    networks:
      - app-network
    command: --log-warnings=1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      TZ: Europe/Stockholm
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

  node:
    image: node:latest
    container_name: node
    restart: unless-stopped
    working_dir: /sveltekit
    command: "npm run dev -- --host 0.0.0.0"
    volumes:
      - ./sveltekit:/sveltekit
    environment:
      TZ: Europe/Stockholm
    networks:
      - app-network
    env_file:
      - .env

  python:
    build: ./python
    container_name: python
    restart: unless-stopped
    environment:
      TZ: Europe/Stockholm
    volumes:
      - ./python:/app #:ro
    networks:
      - app-network
    depends_on:
      mariadb:
        condition: "service_healthy"
    env_file:
      - .env
    ports:
      - "5000:5000"

networks:
  app-network:
    driver: bridge
